# alias
alias g='git'
alias gst='git st'
alias gs='git s'
alias gbr='git br'
alias gl='git l'
alias glp='git lp'
alias gd='git d'
alias gdc='git dc'
alias gsh='git stash'
alias gsp='git stash pop'
alias gsl='git stash list'
alias gpr='git pr'
alias gw='git web'
alias ga='git add'
alias gi='git ci'
